const { getDefaultConfig } = require('expo/metro-config');

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(__dirname);

// Lets Metro resolve the .sql migration files imported by drizzle/migrations.js (generated by
// `npm run db:generate`) — babel-plugin-inline-import then inlines their contents at build time.
config.resolver.sourceExts.push('sql');

module.exports = config;
